Setup

```{r, message = F}
#libraries
library(tidyverse)
library(viridis)
library(latex2exp)

#paths
framePath = paste0(getwd(),"/Images/Frames") #frame location for gif generation
imgPath = paste0(getwd(),"/Images") #output location for images
```

Data Cleaning

```{r, warning = F, echo = F}
kish = read.csv("Data/Kish11-9.csv")
kish = kish[-c(1:39),1:5]
kish = kish[-c(1:2),]
colnames(kish) = c("UTCTime", "LocalTime", "TempC", "Volts", "MagArcsec2") 
kish = mutate(kish, Hour = hour(kish$LocalTime), Obs = seq_along(kish$LocalTime)) %>%
  mutate(DayGroup = ifelse(row_number() >= 162, (row_number() - 161 - 1) %/% 288 + 1, 0))

kish$UTCTime = as.ts(kish$UTCTime)
kish$LocalTime = as.ts(kish$LocalTime)
kish$TempC = as.numeric(kish$TempC)
kish$Volts = as.numeric(kish$Volts)
kish$MagArcsec2 = as.numeric(kish$MagArcsec2)

#remove low volt cases
kish = kish %>%
  filter(Volts>4.8)
```

Plot Setup

```{r, warning = F, echo = F}
#Finding start and end values to center at midnight
#center at midnight, 144 obs each side 143 other
midnights = which(hour(kish$LocalTime) == 0 & minute(kish$LocalTime) == 0)
start = c()
finish = c()
for(i in 2:113){
  start[i] = midnights[i] - 144 #noon of day before
  finish[i] = midnights[i] + 143 #11:55 of day after
}
start = start %>% na.omit()
finish = finish %>% na.omit()

#generating all plots to overlay
plot = ggplot()

for (i in seq_along(start)) {
  plotOutput = kish[c(start[i]:finish[i]), ]
  
  layer = geom_line(data = plotOutput, aes(x = seq_along(MagArcsec2),
                                           y = MagArcsec2,
                                           color = Obs), alpha = 0.5) 
  
  plot = plot + layer
}
```

Combined Plot

```{r, warning=F, message = F}
ylabel = TeX("$\\frac{Magnitude}{Arcsec^2}")

plot+
  ylim(21,5.8)+
  coord_cartesian(xlim = c(50, 250))+
  #bortle scale lines
  # geom_hline(yintercept=21.75, linetype="dashed")+
  # geom_hline(yintercept=21.6, linetype="dashed")+
  # geom_hline(yintercept=21.3, linetype="dashed")+
  # geom_hline(yintercept=20.8, linetype="dashed")+
  # geom_hline(yintercept=20.3, linetype="dashed")+
  # geom_hline(yintercept=19.25, linetype="dashed")+
  # geom_hline(yintercept=18.5, linetype="dashed")+
  # geom_hline(yintercept=18, linetype="dashed")+
  geom_vline(xintercept=144, linetype="dashed", alpha = .3)+
  #colors and labels
  scale_color_viridis_c(option = "viridis", direction = -1,
                        name = "Date",
                        breaks = c(600, 32000),
                        labels = c("7/19", "11/08"))+
  labs(title = "SQM Readings from 7/19/23 - 11/08/23")+
  ylab(ylabel)+
  xlab("")+
  theme(plot.title = element_text(face = "bold"),
        axis.ticks.x = element_blank(),
        axis.title.y = element_text(angle = 0, vjust = .5))+
  scale_x_continuous(breaks = c(72, 144, 216),
                     labels = c("6:00 P.M.",  "12:00 A.M.",  "6:00 A.M."))

#ggsave("combinedPlot.png", path = imgPath, width = 10.67, height = 6) #Note that the dimensions are inches not pixels. Just used a 16:9 aspect ratio.

```

Animated Plot

```{r, warning = F}
#Initially tried gganimate, but couldn't get desired results. Instead used a long and annoying approach of generating each frame individually and creating a gif of them

startdate = as.Date("2023-07-19")

for(i in 1:length(start)){
  plotDate = kish[c(start[i]:finish[i]), ]
  maxSQM = max(plotDate$MagArcsec2)
  
  #Handling ordering
  labelList = c()
  breakList = c()
  if(maxSQM > 20){
    labelList = c(as.character(maxSQM), "", "15", "10", "5") #unsure if leaving 20 out is best choice.
    breakList = c(maxSQM, 20, 15, 10, 5)
  }
  if(maxSQM > 15 & maxSQM <= 20){
    labelList = c("", as.character(maxSQM), "15", "10", "5")
    breakList = c(20, maxSQM, 15, 10, 5)
  }
  if(maxSQM > 10 & maxSQM <= 15){
    labelList = c("20", "15", as.character(maxSQM), "10", "5")
    breakList = c(20, 15, maxSQM, 10, 5)
  }
  if(maxSQM > 5 & maxSQM <= 10){
    labelList = c("20", "15", "10", as.character(maxSQM), "5")  
    breakList = c(20, 15, 10, maxSQM, 5)
  }
  if(maxSQM <= 10){
    labelList = c("20", "15", "10", "5", as.character(maxSQM))
    breakList = c(20, 15, 10, 5, maxSQM)
  }
  
  
  myPlot = ggplot() +
    geom_line(data = plotDate, aes(x = seq_along(MagArcsec2),
                                   y = MagArcsec2,
                                   fill = "black"))+
    labs(title = paste0("SQM Readings from ", as.character(startdate)))+
    xlab("") +
    ylab(ylabel) +
    geom_vline(xintercept=144, linetype="dashed", alpha = .3)+ #midnight
    geom_hline(yintercept = maxSQM, linetype="dashed", alpha=.3)+ #Max line
    theme(plot.title = element_text(face = "bold"),
          legend.position = "none",
          axis.ticks.x = element_blank(),
          axis.title.y = element_text(angle = 0, vjust = .5))+
    scale_x_continuous(breaks = c(72, 144, 216),
                       labels = c("6:00 P.M.",  "12:00 A.M.",  "6:00 A.M."))+
    scale_y_continuous(breaks = breakList,
                       labels = labelList,
                       limits = c(22, 5.8),
                       trans = "reverse")+

    coord_cartesian(xlim = c(50, 250))
  
  frameName = paste0("frame_", as.character(startdate), ".png")
  ggsave(frameName, plot = myPlot, path = framePath, width = 10.67, height = 6)
  
  startdate = startdate+1
}
```

Create gif

```{bash}
#Note that this takes quite a while and is easier to do in terminal, so I commented it out
<!-- cd Images/Frames;convert -delay 20 -loop 0 *.png ../Animation.gif -->
```












