# SPDX-FileCopyrightText: 2024 GLAS Education <angel@glaseducation.org>
# SPDX-License-Identifier: AGPL-3.0-only
version = 1
SPDX-PackageName = "LENSS"
SPDX-PackageSupplier = "GLAS Education <angel@glaseducation.org>"
SPDX-PackageDownloadLocation = "https://github.com/jamesspalding/LENSS"
annotations = []
